# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 745d8b8f3089a81930a21cf268974473d923946d0b7d17c236d9b893ab9ef0518ebb5b80c5aba59d70fdcc4c6e875faca07d30c035d5caffaf190bf56ad8cdda

test:
  secret_key_base: 5435827ebbd5a538dd38913db8ae01b743a729ecf7877c380eccdec826980be4f7b36a321aa2fd6fa138c5b98a9c58a41102f8955a3d1a08f6362d6fd606c018

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
